version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  catalogdb:
   image: mongo

  orderdb:
   image: mcr.microsoft.com/mssql/server:2022-latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  basketdb:
    image: redis:alpine

  rabbitmq:
   image: rabbitmq:3-management-alpine

volumes:
  mongo_data:



