version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8080"

  catalogdb:
   container_name: catalogdb
   ports:
     - "27017:27017"
   volumes:
    - "mongo_data:/data/db"
  
  orderdb:
   container_name: orderdb
   environment:
     SA_PASSWORD: "Passw0rd23"
     ACCEPT_EULA: "Y"
   ports:
    - 1433:1433  


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
  
  basketdb:
    container_name: basketdb
    ports:
      - 6379:6379


