version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  catalogdb:
   image: mongo

  orderdb:
   image: mcr.microsoft.com/mssql/server:2022-latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  basketdb:
    image: redis:alpine

  rabbitmq:
   image: rabbitmq:3-management-alpine

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.Api/Dockerfile

  inventory.grpc:
    image: ${DOCKER_REGISTRY-}inventorygrpc
    build:
      context: .
      dockerfile: Inventory.Grpc/Dockerfile

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Authentication.Api/Dockerfile

volumes:
  mongo_data:






